# Generated by Django 4.2.5 on 2024-02-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_conversationhistory_lastcommand'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profileImage',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
